
package com.example;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-02-14T12:06:17.177+03:00
 * Generated source version: 3.5.5
 *
 */
public final class BelediyePortType_BelediyePortTypeBindingPort_Client {

    private static final QName SERVICE_NAME = new QName("http://belediye.turkiye.gov.tr/v3", "eDevletBelediyeService");

    private BelediyePortType_BelediyePortTypeBindingPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EDevletBelediyeService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        EDevletBelediyeService ss = new EDevletBelediyeService(wsdlURL, SERVICE_NAME);
        BelediyePortType port = ss.getBelediyePortTypeBindingPort();

        {
        System.out.println("Invoking eBeyanSorgula...");
        com.example.EBeyanSorgulamaGType _eBeyanSorgula_part1 = new com.example.EBeyanSorgulamaGType();
        com.example.EBeyanSorgulamaCType _eBeyanSorgula__return = port.eBeyanSorgula(_eBeyanSorgula_part1);
        System.out.println("eBeyanSorgula.result=" + _eBeyanSorgula__return);


        }
        {
        System.out.println("Invoking sosyalYardimBasvuruSorgula...");
        com.example.KisiselSorgulamaGType _sosyalYardimBasvuruSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.SosyalYardimBasvuruSorgulamaCType _sosyalYardimBasvuruSorgula__return = port.sosyalYardimBasvuruSorgula(_sosyalYardimBasvuruSorgula_part1);
        System.out.println("sosyalYardimBasvuruSorgula.result=" + _sosyalYardimBasvuruSorgula__return);


        }
        {
        System.out.println("Invoking yapilandirmaTurSorgula...");
        com.example.YapilandirmaTurSorgulaGType _yapilandirmaTurSorgula_part1 = new com.example.YapilandirmaTurSorgulaGType();
        com.example.YapilandirmaTurSorgulaCType _yapilandirmaTurSorgula__return = port.yapilandirmaTurSorgula(_yapilandirmaTurSorgula_part1);
        System.out.println("yapilandirmaTurSorgula.result=" + _yapilandirmaTurSorgula__return);


        }
        {
        System.out.println("Invoking gunlukFaaliyetSorgula...");
        com.example.SorguParametreType _gunlukFaaliyetSorgula_part1 = new com.example.SorguParametreType();
        com.example.FaaliyetBilgisiCType _gunlukFaaliyetSorgula__return = port.gunlukFaaliyetSorgula(_gunlukFaaliyetSorgula_part1);
        System.out.println("gunlukFaaliyetSorgula.result=" + _gunlukFaaliyetSorgula__return);


        }
        {
        System.out.println("Invoking talepEdilecekEgitimKursSorgula...");
        com.example.SorguParametreType _talepEdilecekEgitimKursSorgula_part1 = new com.example.SorguParametreType();
        com.example.TalepEdilecekEgitimKursSorgulaCType _talepEdilecekEgitimKursSorgula__return = port.talepEdilecekEgitimKursSorgula(_talepEdilecekEgitimKursSorgula_part1);
        System.out.println("talepEdilecekEgitimKursSorgula.result=" + _talepEdilecekEgitimKursSorgula__return);


        }
        {
        System.out.println("Invoking insaatSinifiSorgula...");
        com.example.SorguParametreType _insaatSinifiSorgula_part1 = new com.example.SorguParametreType();
        com.example.InsaatSinifiSorgulamaCtype _insaatSinifiSorgula__return = port.insaatSinifiSorgula(_insaatSinifiSorgula_part1);
        System.out.println("insaatSinifiSorgula.result=" + _insaatSinifiSorgula__return);


        }
        {
        System.out.println("Invoking basvuruNotEkle...");
        com.example.BasvuruNotEkleGType _basvuruNotEkle_part1 = new com.example.BasvuruNotEkleGType();
        com.example.IslemSonucType _basvuruNotEkle__return = port.basvuruNotEkle(_basvuruNotEkle_part1);
        System.out.println("basvuruNotEkle.result=" + _basvuruNotEkle__return);


        }
        {
        System.out.println("Invoking ruhsatSorgula...");
        com.example.RuhsatSorgulaGType _ruhsatSorgula_part1 = new com.example.RuhsatSorgulaGType();
        com.example.RuhsatSorgulamaCType _ruhsatSorgula__return = port.ruhsatSorgula(_ruhsatSorgula_part1);
        System.out.println("ruhsatSorgula.result=" + _ruhsatSorgula__return);


        }
        {
        System.out.println("Invoking encumenKararTarihSorgula...");
        com.example.KararTarihSorgulaGType _encumenKararTarihSorgula_part1 = new com.example.KararTarihSorgulaGType();
        com.example.KararTarihSorgulaCType _encumenKararTarihSorgula__return = port.encumenKararTarihSorgula(_encumenKararTarihSorgula_part1);
        System.out.println("encumenKararTarihSorgula.result=" + _encumenKararTarihSorgula__return);


        }
        {
        System.out.println("Invoking etkinlikBilgisiSorgula...");
        com.example.SorguParametreType _etkinlikBilgisiSorgula_part1 = new com.example.SorguParametreType();
        com.example.EtkinlikBilgisiSorgulaCType _etkinlikBilgisiSorgula__return = port.etkinlikBilgisiSorgula(_etkinlikBilgisiSorgula_part1);
        System.out.println("etkinlikBilgisiSorgula.result=" + _etkinlikBilgisiSorgula__return);


        }
        {
        System.out.println("Invoking egitimKursKategoriSorgula...");
        com.example.SorguParametreType _egitimKursKategoriSorgula_part1 = new com.example.SorguParametreType();
        com.example.EgitimKursKategoriSorgulaCType _egitimKursKategoriSorgula__return = port.egitimKursKategoriSorgula(_egitimKursKategoriSorgula_part1);
        System.out.println("egitimKursKategoriSorgula.result=" + _egitimKursKategoriSorgula__return);


        }
        {
        System.out.println("Invoking bilgilendirmeIstegiYap...");
        com.example.BilgilendirmeIstegiYapGType _bilgilendirmeIstegiYap_part1 = new com.example.BilgilendirmeIstegiYapGType();
        com.example.IslemSonucType _bilgilendirmeIstegiYap__return = port.bilgilendirmeIstegiYap(_bilgilendirmeIstegiYap_part1);
        System.out.println("bilgilendirmeIstegiYap.result=" + _bilgilendirmeIstegiYap__return);


        }
        {
        System.out.println("Invoking sosyalYardimOnBasvuruBilgileriSorgula...");
        com.example.KisiselSorgulamaGType _sosyalYardimOnBasvuruBilgileriSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.SosyalYardimOnBasvuruBilgileriSorgulamaCType _sosyalYardimOnBasvuruBilgileriSorgula__return = port.sosyalYardimOnBasvuruBilgileriSorgula(_sosyalYardimOnBasvuruBilgileriSorgula_part1);
        System.out.println("sosyalYardimOnBasvuruBilgileriSorgula.result=" + _sosyalYardimOnBasvuruBilgileriSorgula__return);


        }
        {
        System.out.println("Invoking ihaleSorgula...");
        com.example.SorguParametreType _ihaleSorgula_part1 = new com.example.SorguParametreType();
        com.example.IhaleSorgulamaCType _ihaleSorgula__return = port.ihaleSorgula(_ihaleSorgula_part1);
        System.out.println("ihaleSorgula.result=" + _ihaleSorgula__return);


        }
        {
        System.out.println("Invoking ozetBorcBilgileriSorgula...");
        com.example.KisiselSorgulamaGType _ozetBorcBilgileriSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.OzetBorcBilgileriSorgulamaCType _ozetBorcBilgileriSorgula__return = port.ozetBorcBilgileriSorgula(_ozetBorcBilgileriSorgula_part1);
        System.out.println("ozetBorcBilgileriSorgula.result=" + _ozetBorcBilgileriSorgula__return);


        }
        {
        System.out.println("Invoking tahsilatSorgula...");
        com.example.TahsilatSorgulamaGType _tahsilatSorgula_part1 = new com.example.TahsilatSorgulamaGType();
        com.example.TahsilatSorgulamaCType _tahsilatSorgula__return = port.tahsilatSorgula(_tahsilatSorgula_part1);
        System.out.println("tahsilatSorgula.result=" + _tahsilatSorgula__return);


        }
        {
        System.out.println("Invoking egitimKursTalepBasvuru...");
        com.example.EgitimKursTalepBasvuruGType _egitimKursTalepBasvuru_part1 = new com.example.EgitimKursTalepBasvuruGType();
        com.example.IslemSonucType _egitimKursTalepBasvuru__return = port.egitimKursTalepBasvuru(_egitimKursTalepBasvuru_part1);
        System.out.println("egitimKursTalepBasvuru.result=" + _egitimKursTalepBasvuru__return);


        }
        {
        System.out.println("Invoking ayarOkuListe...");
        com.example.AyarOkuGType _ayarOkuListe_part1 = new com.example.AyarOkuGType();
        com.example.AyarOkuListeCType _ayarOkuListe__return = port.ayarOkuListe(_ayarOkuListe_part1);
        System.out.println("ayarOkuListe.result=" + _ayarOkuListe__return);


        }
        {
        System.out.println("Invoking mahalleSorgula...");
        com.example.MahalleSorgulamaGType _mahalleSorgula_part1 = new com.example.MahalleSorgulamaGType();
        com.example.MahalleSorgulamaCType _mahalleSorgula__return = port.mahalleSorgula(_mahalleSorgula_part1);
        System.out.println("mahalleSorgula.result=" + _mahalleSorgula__return);


        }
        {
        System.out.println("Invoking kayitliEmlakRayicBelgesiSorgula...");
        com.example.KisiselSorgulamaGType _kayitliEmlakRayicBelgesiSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.KayitliEmlakRayicBelgesiSorgulaCType _kayitliEmlakRayicBelgesiSorgula__return = port.kayitliEmlakRayicBelgesiSorgula(_kayitliEmlakRayicBelgesiSorgula_part1);
        System.out.println("kayitliEmlakRayicBelgesiSorgula.result=" + _kayitliEmlakRayicBelgesiSorgula__return);


        }
        {
        System.out.println("Invoking kayitliBelgeIndir...");
        com.example.KayitliBelgeIndirGType _kayitliBelgeIndir_part1 = new com.example.KayitliBelgeIndirGType();
        com.example.BarkodluBelgeDogrulaCType _kayitliBelgeIndir__return = port.kayitliBelgeIndir(_kayitliBelgeIndir_part1);
        System.out.println("kayitliBelgeIndir.result=" + _kayitliBelgeIndir__return);


        }
        {
        System.out.println("Invoking hayvanSahiplenmeBasvuru...");
        com.example.HayvanSahiplenmeBasvuruGType _hayvanSahiplenmeBasvuru_part1 = new com.example.HayvanSahiplenmeBasvuruGType();
        com.example.IslemSonucType _hayvanSahiplenmeBasvuru__return = port.hayvanSahiplenmeBasvuru(_hayvanSahiplenmeBasvuru_part1);
        System.out.println("hayvanSahiplenmeBasvuru.result=" + _hayvanSahiplenmeBasvuru__return);


        }
        {
        System.out.println("Invoking meclisGundemSorgula...");
        com.example.SorguParametreType _meclisGundemSorgula_part1 = new com.example.SorguParametreType();
        com.example.MeclisGundemSorgulaCType _meclisGundemSorgula__return = port.meclisGundemSorgula(_meclisGundemSorgula_part1);
        System.out.println("meclisGundemSorgula.result=" + _meclisGundemSorgula__return);


        }
        {
        System.out.println("Invoking sicilSorgula...");
        com.example.KisiselSorgulamaGType _sicilSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.SicilSorgulamaCType _sicilSorgula__return = port.sicilSorgula(_sicilSorgula_part1);
        System.out.println("sicilSorgula.result=" + _sicilSorgula__return);


        }
        {
        System.out.println("Invoking vefatBilgisiSorgula...");
        com.example.VefatBilgisiSorgulaGType _vefatBilgisiSorgula_part1 = new com.example.VefatBilgisiSorgulaGType();
        com.example.VefatBilgisiSorgulaCType _vefatBilgisiSorgula__return = port.vefatBilgisiSorgula(_vefatBilgisiSorgula_part1);
        System.out.println("vefatBilgisiSorgula.result=" + _vefatBilgisiSorgula__return);


        }
        {
        System.out.println("Invoking halSorgula...");
        com.example.SorguParametreType _halSorgula_part1 = new com.example.SorguParametreType();
        com.example.HalSorgulaCType _halSorgula__return = port.halSorgula(_halSorgula_part1);
        System.out.println("halSorgula.result=" + _halSorgula__return);


        }
        {
        System.out.println("Invoking halUrunKategoriSorgula...");
        com.example.HalUrunKategoriSorgulaGType _halUrunKategoriSorgula_part1 = new com.example.HalUrunKategoriSorgulaGType();
        com.example.HalUrunKategoriSorgulaCType _halUrunKategoriSorgula__return = port.halUrunKategoriSorgula(_halUrunKategoriSorgula_part1);
        System.out.println("halUrunKategoriSorgula.result=" + _halUrunKategoriSorgula__return);


        }
        {
        System.out.println("Invoking tasinmazBeyanYap...");
        com.example.TasinmazBeyanType _tasinmazBeyanYap_part1 = new com.example.TasinmazBeyanType();
        com.example.IslemSonucType _tasinmazBeyanYap__return = port.tasinmazBeyanYap(_tasinmazBeyanYap_part1);
        System.out.println("tasinmazBeyanYap.result=" + _tasinmazBeyanYap__return);


        }
        {
        System.out.println("Invoking meclisKararSorgula...");
        com.example.KararSorgulaGType _meclisKararSorgula_part1 = new com.example.KararSorgulaGType();
        com.example.KararSorgulaCType _meclisKararSorgula__return = port.meclisKararSorgula(_meclisKararSorgula_part1);
        System.out.println("meclisKararSorgula.result=" + _meclisKararSorgula__return);


        }
        {
        System.out.println("Invoking borcSorgula...");
        com.example.KisiselSorgulamaGType _borcSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.BorcSorgulamaCType _borcSorgula__return = port.borcSorgula(_borcSorgula_part1);
        System.out.println("borcSorgula.result=" + _borcSorgula__return);


        }
        {
        System.out.println("Invoking ilanReklamTurSorgula...");
        com.example.SorguParametreType _ilanReklamTurSorgula_part1 = new com.example.SorguParametreType();
        com.example.IlanReklamTurCtype _ilanReklamTurSorgula__return = port.ilanReklamTurSorgula(_ilanReklamTurSorgula_part1);
        System.out.println("ilanReklamTurSorgula.result=" + _ilanReklamTurSorgula__return);


        }
        {
        System.out.println("Invoking ruhsatBasvuruSorgula...");
        com.example.KisiselSorgulamaGType _ruhsatBasvuruSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.RuhsatBasvuruSorgulamaCType _ruhsatBasvuruSorgula__return = port.ruhsatBasvuruSorgula(_ruhsatBasvuruSorgula_part1);
        System.out.println("ruhsatBasvuruSorgula.result=" + _ruhsatBasvuruSorgula__return);


        }
        {
        System.out.println("Invoking basvuruDurumSorgula...");
        com.example.KisiselSorgulamaGType _basvuruDurumSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.BasvuruDurumCType _basvuruDurumSorgula__return = port.basvuruDurumSorgula(_basvuruDurumSorgula_part1);
        System.out.println("basvuruDurumSorgula.result=" + _basvuruDurumSorgula__return);


        }
        {
        System.out.println("Invoking yapilanSosyaYardimBilgileriSorgula...");
        com.example.YapilanSosyaYardimBilgileriSorgulaGType _yapilanSosyaYardimBilgileriSorgula_part1 = new com.example.YapilanSosyaYardimBilgileriSorgulaGType();
        com.example.YapilanSosyalYardimBilgileriSorgulamaCType _yapilanSosyaYardimBilgileriSorgula__return = port.yapilanSosyaYardimBilgileriSorgula(_yapilanSosyaYardimBilgileriSorgula_part1);
        System.out.println("yapilanSosyaYardimBilgileriSorgula.result=" + _yapilanSosyaYardimBilgileriSorgula__return);


        }
        {
        System.out.println("Invoking insaatTuruSorgula...");
        com.example.InsaatTuruSorgulamaGType _insaatTuruSorgula_part1 = new com.example.InsaatTuruSorgulamaGType();
        com.example.InsaatTuruSorgulamaCtype _insaatTuruSorgula__return = port.insaatTuruSorgula(_insaatTuruSorgula_part1);
        System.out.println("insaatTuruSorgula.result=" + _insaatTuruSorgula__return);


        }
        {
        System.out.println("Invoking suAboneSorgula...");
        com.example.KisiselSorgulamaGType _suAboneSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.SuAboneBilgisiCType _suAboneSorgula__return = port.suAboneSorgula(_suAboneSorgula_part1);
        System.out.println("suAboneSorgula.result=" + _suAboneSorgula__return);


        }
        {
        System.out.println("Invoking yapilandirmaBasvuruSorgula...");
        com.example.KisiselSorgulamaGType _yapilandirmaBasvuruSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.YapilandirmaBasvuruSorgulamaCType _yapilandirmaBasvuruSorgula__return = port.yapilandirmaBasvuruSorgula(_yapilandirmaBasvuruSorgula_part1);
        System.out.println("yapilandirmaBasvuruSorgula.result=" + _yapilandirmaBasvuruSorgula__return);


        }
        {
        System.out.println("Invoking ilanReklamYerSorgula...");
        com.example.IlanReklamYerSorgulamaGType _ilanReklamYerSorgula_part1 = new com.example.IlanReklamYerSorgulamaGType();
        com.example.IlanReklamYerCtype _ilanReklamYerSorgula__return = port.ilanReklamYerSorgula(_ilanReklamYerSorgula_part1);
        System.out.println("ilanReklamYerSorgula.result=" + _ilanReklamYerSorgula__return);


        }
        {
        System.out.println("Invoking ucretTarifesiSorgula...");
        com.example.UcretTarifesiSorgulaGType _ucretTarifesiSorgula_part1 = new com.example.UcretTarifesiSorgulaGType();
        com.example.UcretTarifesiSorgulaCType _ucretTarifesiSorgula__return = port.ucretTarifesiSorgula(_ucretTarifesiSorgula_part1);
        System.out.println("ucretTarifesiSorgula.result=" + _ucretTarifesiSorgula__return);


        }
        {
        System.out.println("Invoking emlakRayicBelgeSorgula...");
        com.example.EmlakRayicBelgeSorgulaGType _emlakRayicBelgeSorgula_part1 = new com.example.EmlakRayicBelgeSorgulaGType();
        com.example.EmlakRayicBelgeSorgulaCType _emlakRayicBelgeSorgula__return = port.emlakRayicBelgeSorgula(_emlakRayicBelgeSorgula_part1);
        System.out.println("emlakRayicBelgeSorgula.result=" + _emlakRayicBelgeSorgula__return);


        }
        {
        System.out.println("Invoking basvuruYap...");
        com.example.BasvuruYapGType _basvuruYap_part1 = new com.example.BasvuruYapGType();
        com.example.BasvuruYapCType _basvuruYap__return = port.basvuruYap(_basvuruYap_part1);
        System.out.println("basvuruYap.result=" + _basvuruYap__return);


        }
        {
        System.out.println("Invoking bordroSorgula...");
        com.example.BordroSorgulaGType _bordroSorgula_part1 = new com.example.BordroSorgulaGType();
        com.example.BordroSorgulaCType _bordroSorgula__return = port.bordroSorgula(_bordroSorgula_part1);
        System.out.println("bordroSorgula.result=" + _bordroSorgula__return);


        }
        {
        System.out.println("Invoking encumenGundemSorgula...");
        com.example.SorguParametreType _encumenGundemSorgula_part1 = new com.example.SorguParametreType();
        com.example.MeclisGundemSorgulaCType _encumenGundemSorgula__return = port.encumenGundemSorgula(_encumenGundemSorgula_part1);
        System.out.println("encumenGundemSorgula.result=" + _encumenGundemSorgula__return);


        }
        {
        System.out.println("Invoking kutuphaneUyelikDetaySorgula...");
        com.example.KutuphaneUyelikDetaySorgulamaGType _kutuphaneUyelikDetaySorgula_part1 = new com.example.KutuphaneUyelikDetaySorgulamaGType();
        com.example.KutuphaneUyelikDetaySorgulamaCType _kutuphaneUyelikDetaySorgula__return = port.kutuphaneUyelikDetaySorgula(_kutuphaneUyelikDetaySorgula_part1);
        System.out.println("kutuphaneUyelikDetaySorgula.result=" + _kutuphaneUyelikDetaySorgula__return);


        }
        {
        System.out.println("Invoking hayvanResimIndir...");
        com.example.HayvanResimIndirGType _hayvanResimIndir_part1 = new com.example.HayvanResimIndirGType();
        com.example.HayvanResimIndirCType _hayvanResimIndir__return = port.hayvanResimIndir(_hayvanResimIndir_part1);
        System.out.println("hayvanResimIndir.result=" + _hayvanResimIndir__return);


        }
        {
        System.out.println("Invoking servisKontrol...");
        com.example.SorguParametreType _servisKontrol_part1 = new com.example.SorguParametreType();
        com.example.IslemSonucType _servisKontrol__return = port.servisKontrol(_servisKontrol_part1);
        System.out.println("servisKontrol.result=" + _servisKontrol__return);


        }
        {
        System.out.println("Invoking ctvKullanimAmaciSorgula...");
        com.example.SorguParametreType _ctvKullanimAmaciSorgula_part1 = new com.example.SorguParametreType();
        com.example.CTVKullanimAmaciCtype _ctvKullanimAmaciSorgula__return = port.ctvKullanimAmaciSorgula(_ctvKullanimAmaciSorgula_part1);
        System.out.println("ctvKullanimAmaciSorgula.result=" + _ctvKullanimAmaciSorgula__return);


        }
        {
        System.out.println("Invoking ilceSorgula...");
        com.example.SorguParametreType _ilceSorgula_part1 = new com.example.SorguParametreType();
        com.example.IlceBilgisiSorgulamaCType _ilceSorgula__return = port.ilceSorgula(_ilceSorgula_part1);
        System.out.println("ilceSorgula.result=" + _ilceSorgula__return);


        }
        {
        System.out.println("Invoking basvuruDetaySorgula...");
        com.example.BasvuruDetaySorgulaGType _basvuruDetaySorgula_part1 = new com.example.BasvuruDetaySorgulaGType();
        com.example.BasvuruDetaySorgulamaCType _basvuruDetaySorgula__return = port.basvuruDetaySorgula(_basvuruDetaySorgula_part1);
        System.out.println("basvuruDetaySorgula.result=" + _basvuruDetaySorgula__return);


        }
        {
        System.out.println("Invoking nikahSalonDurumSorgula...");
        com.example.NikahSalonDurumSorgulaGType _nikahSalonDurumSorgula_part1 = new com.example.NikahSalonDurumSorgulaGType();
        com.example.NikahSalonDurumSorgulaCType _nikahSalonDurumSorgula__return = port.nikahSalonDurumSorgula(_nikahSalonDurumSorgula_part1);
        System.out.println("nikahSalonDurumSorgula.result=" + _nikahSalonDurumSorgula__return);


        }
        {
        System.out.println("Invoking beyanSil...");
        com.example.BeyanSilGType _beyanSil_part1 = new com.example.BeyanSilGType();
        com.example.IslemSonucType _beyanSil__return = port.beyanSil(_beyanSil_part1);
        System.out.println("beyanSil.result=" + _beyanSil__return);


        }
        {
        System.out.println("Invoking egitimKursBilgileriSorgula...");
        com.example.EgitimKursBilgileriSorgulaGType _egitimKursBilgileriSorgula_part1 = new com.example.EgitimKursBilgileriSorgulaGType();
        com.example.EgitimKursBilgileriSorgulaCType _egitimKursBilgileriSorgula__return = port.egitimKursBilgileriSorgula(_egitimKursBilgileriSorgula_part1);
        System.out.println("egitimKursBilgileriSorgula.result=" + _egitimKursBilgileriSorgula__return);


        }
        {
        System.out.println("Invoking suFaturaSorgula...");
        com.example.SuFaturaSorgulamaGType _suFaturaSorgula_part1 = new com.example.SuFaturaSorgulamaGType();
        com.example.SuFaturaSorgulamaCType _suFaturaSorgula__return = port.suFaturaSorgula(_suFaturaSorgula_part1);
        System.out.println("suFaturaSorgula.result=" + _suFaturaSorgula__return);


        }
        {
        System.out.println("Invoking ilanReklamBeyanYap...");
        com.example.IlanReklamBeyanType _ilanReklamBeyanYap_part1 = new com.example.IlanReklamBeyanType();
        com.example.IslemSonucType _ilanReklamBeyanYap__return = port.ilanReklamBeyanYap(_ilanReklamBeyanYap_part1);
        System.out.println("ilanReklamBeyanYap.result=" + _ilanReklamBeyanYap__return);


        }
        {
        System.out.println("Invoking tahakkukSorgula...");
        com.example.TahakkukSorgulamaGType _tahakkukSorgula_part1 = new com.example.TahakkukSorgulamaGType();
        com.example.TahakkukSorgulamaCType _tahakkukSorgula__return = port.tahakkukSorgula(_tahakkukSorgula_part1);
        System.out.println("tahakkukSorgula.result=" + _tahakkukSorgula__return);


        }
        {
        System.out.println("Invoking yapilandirmaBasvuru...");
        com.example.YapilandirmaBasvuruGType _yapilandirmaBasvuru_part1 = new com.example.YapilandirmaBasvuruGType();
        com.example.YapilandirmaBasvuruCType _yapilandirmaBasvuru__return = port.yapilandirmaBasvuru(_yapilandirmaBasvuru_part1);
        System.out.println("yapilandirmaBasvuru.result=" + _yapilandirmaBasvuru__return);


        }
        {
        System.out.println("Invoking kayitliEgitimKursBilgileriSorgula...");
        com.example.KisiselSorgulamaGType _kayitliEgitimKursBilgileriSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.KayitliEgitimKursBilgileriCType _kayitliEgitimKursBilgileriSorgula__return = port.kayitliEgitimKursBilgileriSorgula(_kayitliEgitimKursBilgileriSorgula_part1);
        System.out.println("kayitliEgitimKursBilgileriSorgula.result=" + _kayitliEgitimKursBilgileriSorgula__return);


        }
        {
        System.out.println("Invoking insaatKullanimSekliSorgula...");
        com.example.SorguParametreType _insaatKullanimSekliSorgula_part1 = new com.example.SorguParametreType();
        com.example.InsaatKullanimSekliCtype _insaatKullanimSekliSorgula__return = port.insaatKullanimSekliSorgula(_insaatKullanimSekliSorgula_part1);
        System.out.println("insaatKullanimSekliSorgula.result=" + _insaatKullanimSekliSorgula__return);


        }
        {
        System.out.println("Invoking egitimKursBasvuru...");
        com.example.EgitimKursBasvuruGType _egitimKursBasvuru_part1 = new com.example.EgitimKursBasvuruGType();
        com.example.EgitimKursBasvuruCType _egitimKursBasvuru__return = port.egitimKursBasvuru(_egitimKursBasvuru_part1);
        System.out.println("egitimKursBasvuru.result=" + _egitimKursBasvuru__return);


        }
        {
        System.out.println("Invoking basvuruyuTekrarAc...");
        com.example.BasvuruyuTekrarAcGType _basvuruyuTekrarAc_part1 = new com.example.BasvuruyuTekrarAcGType();
        com.example.IslemSonucType _basvuruyuTekrarAc__return = port.basvuruyuTekrarAc(_basvuruyuTekrarAc_part1);
        System.out.println("basvuruyuTekrarAc.result=" + _basvuruyuTekrarAc__return);


        }
        {
        System.out.println("Invoking nikahSorgula...");
        com.example.NikahSorgulaGType _nikahSorgula_part1 = new com.example.NikahSorgulaGType();
        com.example.NikahSorgulaCType _nikahSorgula__return = port.nikahSorgula(_nikahSorgula_part1);
        System.out.println("nikahSorgula.result=" + _nikahSorgula__return);


        }
        {
        System.out.println("Invoking hizmetSorgula...");
        com.example.HizmetSorgulaGType _hizmetSorgula_part1 = new com.example.HizmetSorgulaGType();
        com.example.HizmetSorgulaCType _hizmetSorgula__return = port.hizmetSorgula(_hizmetSorgula_part1);
        System.out.println("hizmetSorgula.result=" + _hizmetSorgula__return);


        }
        {
        System.out.println("Invoking kutuphaneSorgula...");
        com.example.SorguParametreType _kutuphaneSorgula_part1 = new com.example.SorguParametreType();
        com.example.KutuphaneSorgulaCType _kutuphaneSorgula__return = port.kutuphaneSorgula(_kutuphaneSorgula_part1);
        System.out.println("kutuphaneSorgula.result=" + _kutuphaneSorgula__return);


        }
        {
        System.out.println("Invoking kutuphaneUyelikBasvuruBilgileriSorgula...");
        com.example.KisiselSorgulamaGType _kutuphaneUyelikBasvuruBilgileriSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.KutuphaneUyelikBasvuruBilgileriSorgulamaCType _kutuphaneUyelikBasvuruBilgileriSorgula__return = port.kutuphaneUyelikBasvuruBilgileriSorgula(_kutuphaneUyelikBasvuruBilgileriSorgula_part1);
        System.out.println("kutuphaneUyelikBasvuruBilgileriSorgula.result=" + _kutuphaneUyelikBasvuruBilgileriSorgula__return);


        }
        {
        System.out.println("Invoking kutuphaneUyelikBasvuru...");
        com.example.KutuphaneUyelikBasvuruGType _kutuphaneUyelikBasvuru_part1 = new com.example.KutuphaneUyelikBasvuruGType();
        com.example.IslemSonucType _kutuphaneUyelikBasvuru__return = port.kutuphaneUyelikBasvuru(_kutuphaneUyelikBasvuru_part1);
        System.out.println("kutuphaneUyelikBasvuru.result=" + _kutuphaneUyelikBasvuru__return);


        }
        {
        System.out.println("Invoking sosyalYardimOnBasvuru...");
        com.example.SosyalYardimOnBasvuruGType _sosyalYardimOnBasvuru_part1 = new com.example.SosyalYardimOnBasvuruGType();
        com.example.SosyalYardimOnBasvuruCType _sosyalYardimOnBasvuru__return = port.sosyalYardimOnBasvuru(_sosyalYardimOnBasvuru_part1);
        System.out.println("sosyalYardimOnBasvuru.result=" + _sosyalYardimOnBasvuru__return);


        }
        {
        System.out.println("Invoking sokakCaddeSorgula...");
        com.example.SokakCaddeSorgulamaGType _sokakCaddeSorgula_part1 = new com.example.SokakCaddeSorgulamaGType();
        com.example.SokakCaddeSorgulamaCType _sokakCaddeSorgula__return = port.sokakCaddeSorgula(_sokakCaddeSorgula_part1);
        System.out.println("sokakCaddeSorgula.result=" + _sokakCaddeSorgula__return);


        }
        {
        System.out.println("Invoking barkodluBelgeDogrula...");
        com.example.BarkodluBelgeDogrulaGType _barkodluBelgeDogrula_part1 = new com.example.BarkodluBelgeDogrulaGType();
        com.example.BarkodluBelgeDogrulaCType _barkodluBelgeDogrula__return = port.barkodluBelgeDogrula(_barkodluBelgeDogrula_part1);
        System.out.println("barkodluBelgeDogrula.result=" + _barkodluBelgeDogrula__return);


        }
        {
        System.out.println("Invoking barinaktakiHayvanSorgula...");
        com.example.BarinaktakiHayvanSorgulaGType _barinaktakiHayvanSorgula_part1 = new com.example.BarinaktakiHayvanSorgulaGType();
        com.example.BarinaktakiHayvanSorgulaCType _barinaktakiHayvanSorgula__return = port.barinaktakiHayvanSorgula(_barinaktakiHayvanSorgula_part1);
        System.out.println("barinaktakiHayvanSorgula.result=" + _barinaktakiHayvanSorgula__return);


        }
        {
        System.out.println("Invoking ayarOku...");
        com.example.AyarOkuGType _ayarOku_part1 = new com.example.AyarOkuGType();
        com.example.AyarOkuCType _ayarOku__return = port.ayarOku(_ayarOku_part1);
        System.out.println("ayarOku.result=" + _ayarOku__return);


        }
        {
        System.out.println("Invoking anonimBorcSorgula2...");
        com.example.AnonimBorcSorgulama2GType _anonimBorcSorgula2_part1 = new com.example.AnonimBorcSorgulama2GType();
        com.example.BorcSorgulamaCType _anonimBorcSorgula2__return = port.anonimBorcSorgula2(_anonimBorcSorgula2_part1);
        System.out.println("anonimBorcSorgula2.result=" + _anonimBorcSorgula2__return);


        }
        {
        System.out.println("Invoking egitimKursBasvuruBilgileriSorgula...");
        com.example.KisiselSorgulamaGType _egitimKursBasvuruBilgileriSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.EgitimKursBasvuruBilgileriSorgulamaCType _egitimKursBasvuruBilgileriSorgula__return = port.egitimKursBasvuruBilgileriSorgula(_egitimKursBasvuruBilgileriSorgula_part1);
        System.out.println("egitimKursBasvuruBilgileriSorgula.result=" + _egitimKursBasvuruBilgileriSorgula__return);


        }
        {
        System.out.println("Invoking nikahSalonSorgula...");
        com.example.SorguParametreType _nikahSalonSorgula_part1 = new com.example.SorguParametreType();
        com.example.NikahSalonSorgulaCType _nikahSalonSorgula__return = port.nikahSalonSorgula(_nikahSalonSorgula_part1);
        System.out.println("nikahSalonSorgula.result=" + _nikahSalonSorgula__return);


        }
        {
        System.out.println("Invoking ePostaBilgilendirmeTurleriSorgula...");
        com.example.SorguParametreType _ePostaBilgilendirmeTurleriSorgula_part1 = new com.example.SorguParametreType();
        com.example.BelediyeBilgilendirmeTurSorgulaCType _ePostaBilgilendirmeTurleriSorgula__return = port.ePostaBilgilendirmeTurleriSorgula(_ePostaBilgilendirmeTurleriSorgula_part1);
        System.out.println("ePostaBilgilendirmeTurleriSorgula.result=" + _ePostaBilgilendirmeTurleriSorgula__return);


        }
        {
        System.out.println("Invoking bilgilendirmeIstegiIptal...");
        com.example.KisiselSorgulamaGType _bilgilendirmeIstegiIptal_part1 = new com.example.KisiselSorgulamaGType();
        com.example.IslemSonucType _bilgilendirmeIstegiIptal__return = port.bilgilendirmeIstegiIptal(_bilgilendirmeIstegiIptal_part1);
        System.out.println("bilgilendirmeIstegiIptal.result=" + _bilgilendirmeIstegiIptal__return);


        }
        {
        System.out.println("Invoking beyanBilgisiSorgula...");
        com.example.KisiselSorgulamaGType _beyanBilgisiSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.BeyanBilgileriSorgulamaCType _beyanBilgisiSorgula__return = port.beyanBilgisiSorgula(_beyanBilgisiSorgula_part1);
        System.out.println("beyanBilgisiSorgula.result=" + _beyanBilgisiSorgula__return);


        }
        {
        System.out.println("Invoking bordroDonemSorgula...");
        com.example.KisiselSorgulamaGType _bordroDonemSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.BordroDonemSorgulaCType _bordroDonemSorgula__return = port.bordroDonemSorgula(_bordroDonemSorgula_part1);
        System.out.println("bordroDonemSorgula.result=" + _bordroDonemSorgula__return);


        }
        {
        System.out.println("Invoking copToplamaBilgisiSorgula...");
        com.example.CopToplamaBilgisiSorgulaGType _copToplamaBilgisiSorgula_part1 = new com.example.CopToplamaBilgisiSorgulaGType();
        com.example.CopToplamaBilgisiSorgulaCType _copToplamaBilgisiSorgula__return = port.copToplamaBilgisiSorgula(_copToplamaBilgisiSorgula_part1);
        System.out.println("copToplamaBilgisiSorgula.result=" + _copToplamaBilgisiSorgula__return);


        }
        {
        System.out.println("Invoking tasinmazBeyanBilgisiSorgula...");
        com.example.KisiselSorgulamaGType _tasinmazBeyanBilgisiSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.TasinmazBeyanBilgileriSorgulaCType _tasinmazBeyanBilgisiSorgula__return = port.tasinmazBeyanBilgisiSorgula(_tasinmazBeyanBilgisiSorgula_part1);
        System.out.println("tasinmazBeyanBilgisiSorgula.result=" + _tasinmazBeyanBilgisiSorgula__return);


        }
        {
        System.out.println("Invoking mezarYeriSorgula...");
        com.example.MezarYeriSorgulaGType _mezarYeriSorgula_part1 = new com.example.MezarYeriSorgulaGType();
        com.example.MezarYeriSorgulaCType _mezarYeriSorgula__return = port.mezarYeriSorgula(_mezarYeriSorgula_part1);
        System.out.println("mezarYeriSorgula.result=" + _mezarYeriSorgula__return);


        }
        {
        System.out.println("Invoking arsaRayicBedelSorgula...");
        com.example.ArsaRayicBedelBilgisiGType _arsaRayicBedelSorgula_part1 = new com.example.ArsaRayicBedelBilgisiGType();
        com.example.ArsaRayicBedelBilgisiCType _arsaRayicBedelSorgula__return = port.arsaRayicBedelSorgula(_arsaRayicBedelSorgula_part1);
        System.out.println("arsaRayicBedelSorgula.result=" + _arsaRayicBedelSorgula__return);


        }
        {
        System.out.println("Invoking askidakiImarPlaniSorgula...");
        com.example.SorguParametreType _askidakiImarPlaniSorgula_part1 = new com.example.SorguParametreType();
        com.example.AskidakiImarPlaniSorgulaCType _askidakiImarPlaniSorgula__return = port.askidakiImarPlaniSorgula(_askidakiImarPlaniSorgula_part1);
        System.out.println("askidakiImarPlaniSorgula.result=" + _askidakiImarPlaniSorgula__return);


        }
        {
        System.out.println("Invoking meclisKararTarihSorgula...");
        com.example.KararTarihSorgulaGType _meclisKararTarihSorgula_part1 = new com.example.KararTarihSorgulaGType();
        com.example.KararTarihSorgulaCType _meclisKararTarihSorgula__return = port.meclisKararTarihSorgula(_meclisKararTarihSorgula_part1);
        System.out.println("meclisKararTarihSorgula.result=" + _meclisKararTarihSorgula__return);


        }
        {
        System.out.println("Invoking egitimKursYeriSorgula...");
        com.example.EgitimKursYeriSorgulaGType _egitimKursYeriSorgula_part1 = new com.example.EgitimKursYeriSorgulaGType();
        com.example.EgitimKursYeriSorgulaCType _egitimKursYeriSorgula__return = port.egitimKursYeriSorgula(_egitimKursYeriSorgula_part1);
        System.out.println("egitimKursYeriSorgula.result=" + _egitimKursYeriSorgula__return);


        }
        {
        System.out.println("Invoking katalogTarama...");
        com.example.KatalogTaramaGType _katalogTarama_part1 = new com.example.KatalogTaramaGType();
        com.example.KatalogTaramaCType _katalogTarama__return = port.katalogTarama(_katalogTarama_part1);
        System.out.println("katalogTarama.result=" + _katalogTarama__return);


        }
        {
        System.out.println("Invoking makbuzIndir...");
        com.example.MakbuzIndirGType _makbuzIndir_part1 = new com.example.MakbuzIndirGType();
        com.example.TahsilatDekontIndirCType _makbuzIndir__return = port.makbuzIndir(_makbuzIndir_part1);
        System.out.println("makbuzIndir.result=" + _makbuzIndir__return);


        }
        {
        System.out.println("Invoking halUrunBilgisiSorgula...");
        com.example.HalUrunBilgisiSorgulaGType _halUrunBilgisiSorgula_part1 = new com.example.HalUrunBilgisiSorgulaGType();
        com.example.HalUrunBilgisiSorgulaCType _halUrunBilgisiSorgula__return = port.halUrunBilgisiSorgula(_halUrunBilgisiSorgula_part1);
        System.out.println("halUrunBilgisiSorgula.result=" + _halUrunBilgisiSorgula__return);


        }
        {
        System.out.println("Invoking encumenKararSorgula...");
        com.example.KararSorgulaGType _encumenKararSorgula_part1 = new com.example.KararSorgulaGType();
        com.example.KararSorgulaCType _encumenKararSorgula__return = port.encumenKararSorgula(_encumenKararSorgula_part1);
        System.out.println("encumenKararSorgula.result=" + _encumenKararSorgula__return);


        }
        {
        System.out.println("Invoking anonimBorcSorgula...");
        com.example.AnonimBorcSorgulamaGType _anonimBorcSorgula_part1 = new com.example.AnonimBorcSorgulamaGType();
        com.example.BorcSorgulamaCType _anonimBorcSorgula__return = port.anonimBorcSorgula(_anonimBorcSorgula_part1);
        System.out.println("anonimBorcSorgula.result=" + _anonimBorcSorgula__return);


        }
        {
        System.out.println("Invoking basvuruTipiSorgula...");
        com.example.SorguParametreType _basvuruTipiSorgula_part1 = new com.example.SorguParametreType();
        com.example.BasvuruTipiBilgisiCType _basvuruTipiSorgula__return = port.basvuruTipiSorgula(_basvuruTipiSorgula_part1);
        System.out.println("basvuruTipiSorgula.result=" + _basvuruTipiSorgula__return);


        }
        {
        System.out.println("Invoking belediyeMudurlukSorgula...");
        com.example.SorguParametreType _belediyeMudurlukSorgula_part1 = new com.example.SorguParametreType();
        com.example.BelediyeMudurlukSorgulaCType _belediyeMudurlukSorgula__return = port.belediyeMudurlukSorgula(_belediyeMudurlukSorgula_part1);
        System.out.println("belediyeMudurlukSorgula.result=" + _belediyeMudurlukSorgula__return);


        }
        {
        System.out.println("Invoking imarBilgisiSorgula...");
        com.example.ImarBilgisiSorgulamaGType _imarBilgisiSorgula_part1 = new com.example.ImarBilgisiSorgulamaGType();
        com.example.ImarBilgisiSorgulamaCType _imarBilgisiSorgula__return = port.imarBilgisiSorgula(_imarBilgisiSorgula_part1);
        System.out.println("imarBilgisiSorgula.result=" + _imarBilgisiSorgula__return);


        }
        {
        System.out.println("Invoking kutuphaneUyelikSorgula...");
        com.example.KisiselSorgulamaGType _kutuphaneUyelikSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.KutuphaneUyelikSorgulamaCType _kutuphaneUyelikSorgula__return = port.kutuphaneUyelikSorgula(_kutuphaneUyelikSorgula_part1);
        System.out.println("kutuphaneUyelikSorgula.result=" + _kutuphaneUyelikSorgula__return);


        }
        {
        System.out.println("Invoking hayvanSahiplenmeBasvuruBilgileriSorgula...");
        com.example.KisiselSorgulamaGType _hayvanSahiplenmeBasvuruBilgileriSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.HayvanSahiplenmeBasvuruBilgileriSorgulaCType _hayvanSahiplenmeBasvuruBilgileriSorgula__return = port.hayvanSahiplenmeBasvuruBilgileriSorgula(_hayvanSahiplenmeBasvuruBilgileriSorgula_part1);
        System.out.println("hayvanSahiplenmeBasvuruBilgileriSorgula.result=" + _hayvanSahiplenmeBasvuruBilgileriSorgula__return);


        }
        {
        System.out.println("Invoking nobetciEczaneSorgula...");
        com.example.NobetciEczaneSorgulamaGType _nobetciEczaneSorgula_part1 = new com.example.NobetciEczaneSorgulamaGType();
        com.example.NobetciEczaneSorgulamaCType _nobetciEczaneSorgula__return = port.nobetciEczaneSorgula(_nobetciEczaneSorgula_part1);
        System.out.println("nobetciEczaneSorgula.result=" + _nobetciEczaneSorgula__return);


        }
        {
        System.out.println("Invoking bilgilendirmeIstegiSorgula...");
        com.example.KisiselSorgulamaGType _bilgilendirmeIstegiSorgula_part1 = new com.example.KisiselSorgulamaGType();
        com.example.BilgilendirmeIstegiSorgulaCType _bilgilendirmeIstegiSorgula__return = port.bilgilendirmeIstegiSorgula(_bilgilendirmeIstegiSorgula_part1);
        System.out.println("bilgilendirmeIstegiSorgula.result=" + _bilgilendirmeIstegiSorgula__return);


        }
        {
        System.out.println("Invoking tahsilatDekontIndir...");
        com.example.TahsilatDekontIndirGType _tahsilatDekontIndir_part1 = new com.example.TahsilatDekontIndirGType();
        com.example.TahsilatDekontIndirCType _tahsilatDekontIndir__return = port.tahsilatDekontIndir(_tahsilatDekontIndir_part1);
        System.out.println("tahsilatDekontIndir.result=" + _tahsilatDekontIndir__return);


        }
        {
        System.out.println("Invoking mezarlikSorgula...");
        com.example.SorguParametreType _mezarlikSorgula_part1 = new com.example.SorguParametreType();
        com.example.MezarlikSorgulaCType _mezarlikSorgula__return = port.mezarlikSorgula(_mezarlikSorgula_part1);
        System.out.println("mezarlikSorgula.result=" + _mezarlikSorgula__return);


        }
        {
        System.out.println("Invoking evrakSorgula...");
        com.example.EvrakSorgulamaGType _evrakSorgula_part1 = new com.example.EvrakSorgulamaGType();
        com.example.EvrakSorgulamaCType _evrakSorgula__return = port.evrakSorgula(_evrakSorgula_part1);
        System.out.println("evrakSorgula.result=" + _evrakSorgula__return);


        }
        {
        System.out.println("Invoking cevreTemizlikBeyanYap...");
        com.example.CevreTemizlikBeyanType _cevreTemizlikBeyanYap_part1 = new com.example.CevreTemizlikBeyanType();
        com.example.IslemSonucType _cevreTemizlikBeyanYap__return = port.cevreTemizlikBeyanYap(_cevreTemizlikBeyanYap_part1);
        System.out.println("cevreTemizlikBeyanYap.result=" + _cevreTemizlikBeyanYap__return);


        }
        {
        System.out.println("Invoking smsBilgilendirmeTurleriSorgula...");
        com.example.SorguParametreType _smsBilgilendirmeTurleriSorgula_part1 = new com.example.SorguParametreType();
        com.example.BelediyeBilgilendirmeTurSorgulaCType _smsBilgilendirmeTurleriSorgula__return = port.smsBilgilendirmeTurleriSorgula(_smsBilgilendirmeTurleriSorgula_part1);
        System.out.println("smsBilgilendirmeTurleriSorgula.result=" + _smsBilgilendirmeTurleriSorgula__return);


        }

        System.exit(0);
    }

}
