package com.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-02-14T12:06:17.228+03:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://belediye.turkiye.gov.tr/v3", name = "BelediyePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BelediyePortType {

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/eBeyanSorgula")
    @WebResult(name = "eBeyanSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public EBeyanSorgulamaCType eBeyanSorgula(

        @WebParam(partName = "part1", name = "eBeyanSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        EBeyanSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/sosyalYardimBasvuruSorgula")
    @WebResult(name = "sosyalYardimBasvuruSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public SosyalYardimBasvuruSorgulamaCType sosyalYardimBasvuruSorgula(

        @WebParam(partName = "part1", name = "sosyalYardimBasvuruSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/yapilandirmaTurSorgula")
    @WebResult(name = "yapilandirmaTurSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public YapilandirmaTurSorgulaCType yapilandirmaTurSorgula(

        @WebParam(partName = "part1", name = "yapilandirmaTurSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        YapilandirmaTurSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/gunlukFaaliyetSorgula")
    @WebResult(name = "gunlukFaaliyetSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public FaaliyetBilgisiCType gunlukFaaliyetSorgula(

        @WebParam(partName = "part1", name = "gunlukFaaliyetSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/talepEdilecekEgitimKursSorgula")
    @WebResult(name = "talepEdilecekEgitimKursSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public TalepEdilecekEgitimKursSorgulaCType talepEdilecekEgitimKursSorgula(

        @WebParam(partName = "part1", name = "talepEdilecekEgitimKursSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/insaatSinifiSorgula")
    @WebResult(name = "insaatSinifiSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public InsaatSinifiSorgulamaCtype insaatSinifiSorgula(

        @WebParam(partName = "part1", name = "insaatSinifiSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/basvuruNotEkle")
    @WebResult(name = "basvuruNotEkleC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType basvuruNotEkle(

        @WebParam(partName = "part1", name = "basvuruNotEkleG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        BasvuruNotEkleGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ruhsatSorgula")
    @WebResult(name = "ruhsatSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public RuhsatSorgulamaCType ruhsatSorgula(

        @WebParam(partName = "part1", name = "ruhsatSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        RuhsatSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/encumenKararTarihSorgula")
    @WebResult(name = "encumenKararTarihSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KararTarihSorgulaCType encumenKararTarihSorgula(

        @WebParam(partName = "part1", name = "encumenKararTarihSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KararTarihSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/etkinlikBilgisiSorgula")
    @WebResult(name = "etkinlikBilgisiSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public EtkinlikBilgisiSorgulaCType etkinlikBilgisiSorgula(

        @WebParam(partName = "part1", name = "etkinlikBilgisiSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/egitimKursKategoriSorgula")
    @WebResult(name = "egitimKursKategoriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public EgitimKursKategoriSorgulaCType egitimKursKategoriSorgula(

        @WebParam(partName = "part1", name = "egitimKursKategoriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/bilgilendirmeIstegiYap")
    @WebResult(name = "bilgilendirmeIstegiYapC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType bilgilendirmeIstegiYap(

        @WebParam(partName = "part1", name = "bilgilendirmeIstegiYapG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        BilgilendirmeIstegiYapGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/sosyalYardimOnBasvuruBilgileriSorgula")
    @WebResult(name = "sosyalYardimOnBasvuruBilgileriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public SosyalYardimOnBasvuruBilgileriSorgulamaCType sosyalYardimOnBasvuruBilgileriSorgula(

        @WebParam(partName = "part1", name = "sosyalYardimOnBasvuruBilgileriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ihaleSorgula")
    @WebResult(name = "ihaleSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IhaleSorgulamaCType ihaleSorgula(

        @WebParam(partName = "part1", name = "ihaleSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ozetBorcBilgileriSorgula")
    @WebResult(name = "ozetBorcBilgileriSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public OzetBorcBilgileriSorgulamaCType ozetBorcBilgileriSorgula(

        @WebParam(partName = "part1", name = "ozetBorcBilgileriSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/tahsilatSorgula")
    @WebResult(name = "tahsilatSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public TahsilatSorgulamaCType tahsilatSorgula(

        @WebParam(partName = "part1", name = "tahsilatSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        TahsilatSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/egitimKursTalepBasvuru")
    @WebResult(name = "egitimKursTalepBasvuruC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType egitimKursTalepBasvuru(

        @WebParam(partName = "part1", name = "egitimKursTalepBasvuruG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        EgitimKursTalepBasvuruGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ayarOkuListe")
    @WebResult(name = "ayarOkuListeC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public AyarOkuListeCType ayarOkuListe(

        @WebParam(partName = "part1", name = "ayarOkuListeG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        AyarOkuGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/mahalleBilgisiSorgulama")
    @WebResult(name = "mahalleSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public MahalleSorgulamaCType mahalleSorgula(

        @WebParam(partName = "part1", name = "mahalleSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        MahalleSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/kayitliEmlakRayicBelgesiSorgula")
    @WebResult(name = "kayitliEmlakRayicBelgesiSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KayitliEmlakRayicBelgesiSorgulaCType kayitliEmlakRayicBelgesiSorgula(

        @WebParam(partName = "part1", name = "kayitliEmlakRayicBelgesiSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/kayitliBelgeIndir")
    @WebResult(name = "kayitliBelgeIndirC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BarkodluBelgeDogrulaCType kayitliBelgeIndir(

        @WebParam(partName = "part1", name = "kayitliBelgeIndirG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KayitliBelgeIndirGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/hayvanSahiplenmeBasvuru")
    @WebResult(name = "hayvanSahiplenmeBasvuruC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType hayvanSahiplenmeBasvuru(

        @WebParam(partName = "part1", name = "hayvanSahiplenmeBasvuruG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        HayvanSahiplenmeBasvuruGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/meclisGundemSorgula")
    @WebResult(name = "meclisGundemSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public MeclisGundemSorgulaCType meclisGundemSorgula(

        @WebParam(partName = "part1", name = "meclisGundemSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/sicilSorgulama")
    @WebResult(name = "sicilSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public SicilSorgulamaCType sicilSorgula(

        @WebParam(partName = "part1", name = "sicilSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/vefatBilgisiSorgula")
    @WebResult(name = "vefatBilgisiSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public VefatBilgisiSorgulaCType vefatBilgisiSorgula(

        @WebParam(partName = "part1", name = "vefatBilgisiSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        VefatBilgisiSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/halSorgula")
    @WebResult(name = "halSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public HalSorgulaCType halSorgula(

        @WebParam(partName = "part1", name = "halSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/halUrunKategoriSorgula")
    @WebResult(name = "halUrunKategoriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public HalUrunKategoriSorgulaCType halUrunKategoriSorgula(

        @WebParam(partName = "part1", name = "halUrunKategoriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        HalUrunKategoriSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/tasinmazBeyanYap")
    @WebResult(name = "tasinmazBeyanC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType tasinmazBeyanYap(

        @WebParam(partName = "part1", name = "tasinmazBeyanG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        TasinmazBeyanType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/meclisKararSorgula")
    @WebResult(name = "meclisKararSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KararSorgulaCType meclisKararSorgula(

        @WebParam(partName = "part1", name = "meclisKararSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KararSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/borcSorgula")
    @WebResult(name = "borcSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BorcSorgulamaCType borcSorgula(

        @WebParam(partName = "part1", name = "borcSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ilanReklamTurSorgula")
    @WebResult(name = "ilanReklamTurSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IlanReklamTurCtype ilanReklamTurSorgula(

        @WebParam(partName = "part1", name = "ilanReklamTurSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ruhsatBasvuruSorgula")
    @WebResult(name = "ruhsatBasvuruSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public RuhsatBasvuruSorgulamaCType ruhsatBasvuruSorgula(

        @WebParam(partName = "part1", name = "ruhsatBasvuruSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/bBasvuruDurumSorgula")
    @WebResult(name = "basvuruDurumSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BasvuruDurumCType basvuruDurumSorgula(

        @WebParam(partName = "part1", name = "basvuruDurumSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/yapilanSosyaYardimBilgileriSorgula")
    @WebResult(name = "yapilanSosyaYardimBilgileriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public YapilanSosyalYardimBilgileriSorgulamaCType yapilanSosyaYardimBilgileriSorgula(

        @WebParam(partName = "part1", name = "yapilanSosyaYardimBilgileriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        YapilanSosyaYardimBilgileriSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/insaatTuruSorgula")
    @WebResult(name = "insaatTuruSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public InsaatTuruSorgulamaCtype insaatTuruSorgula(

        @WebParam(partName = "part1", name = "insaatTuruSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        InsaatTuruSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/suAboneSorgula")
    @WebResult(name = "suAboneSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public SuAboneBilgisiCType suAboneSorgula(

        @WebParam(partName = "part1", name = "suAboneSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/yapilandirmaBasvuruSorgula")
    @WebResult(name = "yapilandirmaBasvuruSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public YapilandirmaBasvuruSorgulamaCType yapilandirmaBasvuruSorgula(

        @WebParam(partName = "part1", name = "yapilandirmaBasvuruSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ilanReklamYerSorgula")
    @WebResult(name = "ilanReklamYerSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IlanReklamYerCtype ilanReklamYerSorgula(

        @WebParam(partName = "part1", name = "ilanReklamYerSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        IlanReklamYerSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ucretTarifesiSorgula")
    @WebResult(name = "ucretTarifesiSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public UcretTarifesiSorgulaCType ucretTarifesiSorgula(

        @WebParam(partName = "part1", name = "ucretTarifesiSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        UcretTarifesiSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/emlakRayicBelgeSorgula")
    @WebResult(name = "emlakRayicBelgeSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public EmlakRayicBelgeSorgulaCType emlakRayicBelgeSorgula(

        @WebParam(partName = "part1", name = "emlakRayicBelgeSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        EmlakRayicBelgeSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/basvuruYap")
    @WebResult(name = "basvuruYapC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BasvuruYapCType basvuruYap(

        @WebParam(partName = "part1", name = "basvuruYapG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        BasvuruYapGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/bordroSorgula")
    @WebResult(name = "bordroSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BordroSorgulaCType bordroSorgula(

        @WebParam(partName = "part1", name = "bordroSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        BordroSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/encumenGundemSorgula")
    @WebResult(name = "encumenGundemSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public MeclisGundemSorgulaCType encumenGundemSorgula(

        @WebParam(partName = "part1", name = "encumenGundemSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/kutuphaneUyelikDetaySorgula")
    @WebResult(name = "kutuphaneUyelikDetaySorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KutuphaneUyelikDetaySorgulamaCType kutuphaneUyelikDetaySorgula(

        @WebParam(partName = "part1", name = "kutuphaneUyelikDetaySorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KutuphaneUyelikDetaySorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/hayvanResimIndir")
    @WebResult(name = "hayvanResimIndirC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public HayvanResimIndirCType hayvanResimIndir(

        @WebParam(partName = "part1", name = "hayvanResimIndirG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        HayvanResimIndirGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/sistemKontrol")
    @WebResult(name = "echoC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType servisKontrol(

        @WebParam(partName = "part1", name = "echoG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(operationName = "CTVKullanimAmaciSorgula", action = "http://belediye.turkiye.gov.tr/v3/CTVKullanimAmaciSorgula")
    @WebResult(name = "CTVKullanimAmaciSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public CTVKullanimAmaciCtype ctvKullanimAmaciSorgula(

        @WebParam(partName = "part1", name = "CTVKullanimAmaciSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ilceSorgula")
    @WebResult(name = "ilceSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IlceBilgisiSorgulamaCType ilceSorgula(

        @WebParam(partName = "part1", name = "ilceSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/basvuruDetaySorgula")
    @WebResult(name = "basvuruDetaySorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BasvuruDetaySorgulamaCType basvuruDetaySorgula(

        @WebParam(partName = "part1", name = "basvuruDetaySorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        BasvuruDetaySorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/nikahSalonDurumSorgula")
    @WebResult(name = "nikahSalonDurumSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public NikahSalonDurumSorgulaCType nikahSalonDurumSorgula(

        @WebParam(partName = "part1", name = "nikahSalonDurumSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        NikahSalonDurumSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/beyanSil")
    @WebResult(name = "beyanSilC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType beyanSil(

        @WebParam(partName = "part1", name = "beyanSilG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        BeyanSilGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/egitimKursBilgileriSorgula")
    @WebResult(name = "egitimKursBilgileriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public EgitimKursBilgileriSorgulaCType egitimKursBilgileriSorgula(

        @WebParam(partName = "part1", name = "egitimKursBilgileriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        EgitimKursBilgileriSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/suFaturaSorgula")
    @WebResult(name = "suFaturaSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public SuFaturaSorgulamaCType suFaturaSorgula(

        @WebParam(partName = "part1", name = "suFaturaSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SuFaturaSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ilanReklamBeyanYap")
    @WebResult(name = "ilanReklamBeyanC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType ilanReklamBeyanYap(

        @WebParam(partName = "part1", name = "ilanReklamBeyanG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        IlanReklamBeyanType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/tahakkukSorgula")
    @WebResult(name = "tahakkukSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public TahakkukSorgulamaCType tahakkukSorgula(

        @WebParam(partName = "part1", name = "tahakkukSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        TahakkukSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/yapilandirmaBasvuru")
    @WebResult(name = "yapilandirmaBasvuruC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public YapilandirmaBasvuruCType yapilandirmaBasvuru(

        @WebParam(partName = "part1", name = "yapilandirmaBasvuruG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        YapilandirmaBasvuruGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/kayitliEgitimKursBilgileriSorgula")
    @WebResult(name = "kayitliEgitimKursBilgileriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KayitliEgitimKursBilgileriCType kayitliEgitimKursBilgileriSorgula(

        @WebParam(partName = "part1", name = "kayitliEgitimKursBilgileriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/insaatKullanimSekliSorgula")
    @WebResult(name = "insaatKullanimSekliSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public InsaatKullanimSekliCtype insaatKullanimSekliSorgula(

        @WebParam(partName = "part1", name = "insaatKullanimSekliSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/egitimKursBasvuru")
    @WebResult(name = "egitimKursBasvuruC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public EgitimKursBasvuruCType egitimKursBasvuru(

        @WebParam(partName = "part1", name = "egitimKursBasvuruG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        EgitimKursBasvuruGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/basvuruyuTekrarAc")
    @WebResult(name = "basvuruyuTekrarAcC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType basvuruyuTekrarAc(

        @WebParam(partName = "part1", name = "basvuruyuTekrarAcG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        BasvuruyuTekrarAcGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/nikahSorgula")
    @WebResult(name = "nikahSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public NikahSorgulaCType nikahSorgula(

        @WebParam(partName = "part1", name = "nikahSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        NikahSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/hizmetSorgula")
    @WebResult(name = "hizmetSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public HizmetSorgulaCType hizmetSorgula(

        @WebParam(partName = "part1", name = "hizmetSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        HizmetSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/kutuphaneSorgula")
    @WebResult(name = "kutuphaneSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KutuphaneSorgulaCType kutuphaneSorgula(

        @WebParam(partName = "part1", name = "kutuphaneSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/kutuphaneUyelikBasvuruBilgileriSorgula")
    @WebResult(name = "kutuphaneUyelikBasvuruBilgileriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KutuphaneUyelikBasvuruBilgileriSorgulamaCType kutuphaneUyelikBasvuruBilgileriSorgula(

        @WebParam(partName = "part1", name = "kutuphaneUyelikBasvuruBilgileriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/kutuphaneUyelikBasvuru")
    @WebResult(name = "kutuphaneUyelikBasvuruC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType kutuphaneUyelikBasvuru(

        @WebParam(partName = "part1", name = "kutuphaneUyelikBasvuruG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KutuphaneUyelikBasvuruGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/sosyalYardimOnBasvuru")
    @WebResult(name = "sosyalYardimOnBasvuruC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public SosyalYardimOnBasvuruCType sosyalYardimOnBasvuru(

        @WebParam(partName = "part1", name = "sosyalYardimOnBasvuruG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SosyalYardimOnBasvuruGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/sokakCaddeSorgulama")
    @WebResult(name = "sokakCaddeSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public SokakCaddeSorgulamaCType sokakCaddeSorgula(

        @WebParam(partName = "part1", name = "sokakCaddeSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SokakCaddeSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/barkodluBelgeDogrula")
    @WebResult(name = "barkodluBelgeDogrulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BarkodluBelgeDogrulaCType barkodluBelgeDogrula(

        @WebParam(partName = "part1", name = "barkodluBelgeDogrulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        BarkodluBelgeDogrulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/barinaktakiHayvanSorgula")
    @WebResult(name = "barinaktakiHayvanSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BarinaktakiHayvanSorgulaCType barinaktakiHayvanSorgula(

        @WebParam(partName = "part1", name = "barinaktakiHayvanSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        BarinaktakiHayvanSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/ayarOku")
    @WebResult(name = "ayarOkuC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public AyarOkuCType ayarOku(

        @WebParam(partName = "part1", name = "ayarOkuG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        AyarOkuGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/anonimBorcSorgula2")
    @WebResult(name = "borcSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BorcSorgulamaCType anonimBorcSorgula2(

        @WebParam(partName = "part1", name = "anonimBorcSorgulama2G", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        AnonimBorcSorgulama2GType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/egitimKursBasvuruBilgileriSorgula")
    @WebResult(name = "egitimKursBasvuruBilgileriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public EgitimKursBasvuruBilgileriSorgulamaCType egitimKursBasvuruBilgileriSorgula(

        @WebParam(partName = "part1", name = "egitimKursBasvuruBilgileriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/nikahSalonSorgula")
    @WebResult(name = "nikahSalonSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public NikahSalonSorgulaCType nikahSalonSorgula(

        @WebParam(partName = "part1", name = "nikahSalonSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/epostaBilgilendirmeTurleriSorgula")
    @WebResult(name = "epostaBilgilendirmeTurleriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BelediyeBilgilendirmeTurSorgulaCType ePostaBilgilendirmeTurleriSorgula(

        @WebParam(partName = "part1", name = "epostaBilgilendirmeTurleriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/bilgilendirmeIstegiIptal")
    @WebResult(name = "bilgilendirmeIstegiIptalC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType bilgilendirmeIstegiIptal(

        @WebParam(partName = "part1", name = "bilgilendirmeIstegiIptalG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/beyanBilgisiSorgula")
    @WebResult(name = "beyanBilgisiSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BeyanBilgileriSorgulamaCType beyanBilgisiSorgula(

        @WebParam(partName = "part1", name = "beyanBilgisiSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/bordroDonemSorgula")
    @WebResult(name = "bordroDonemSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BordroDonemSorgulaCType bordroDonemSorgula(

        @WebParam(partName = "part1", name = "bordroDonemSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/copToplamaBilgisiSorgula")
    @WebResult(name = "copToplamaBilgisiSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public CopToplamaBilgisiSorgulaCType copToplamaBilgisiSorgula(

        @WebParam(partName = "part1", name = "copToplamaBilgisiSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        CopToplamaBilgisiSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/tasinmazBeyanBilgisiSorgula")
    @WebResult(name = "tasinmazBeyanBilgisiSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public TasinmazBeyanBilgileriSorgulaCType tasinmazBeyanBilgisiSorgula(

        @WebParam(partName = "part1", name = "tasinmazBeyanBilgisiSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/mezarYeriSorgula")
    @WebResult(name = "mezarYeriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public MezarYeriSorgulaCType mezarYeriSorgula(

        @WebParam(partName = "part1", name = "mezarYeriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        MezarYeriSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/arsaRayicBedelSorgula")
    @WebResult(name = "arsaRayicBedelSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public ArsaRayicBedelBilgisiCType arsaRayicBedelSorgula(

        @WebParam(partName = "part1", name = "arsaRayicBedelSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        ArsaRayicBedelBilgisiGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/askidakiImarPlaniSorgula")
    @WebResult(name = "askidakiImarPlaniSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public AskidakiImarPlaniSorgulaCType askidakiImarPlaniSorgula(

        @WebParam(partName = "part1", name = "askidakiImarPlaniSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/meclisKararTarihSorgula")
    @WebResult(name = "meclisKararTarihSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KararTarihSorgulaCType meclisKararTarihSorgula(

        @WebParam(partName = "part1", name = "meclisKararTarihSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KararTarihSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/egitimKursYeriSorgula")
    @WebResult(name = "egitimKursYeriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public EgitimKursYeriSorgulaCType egitimKursYeriSorgula(

        @WebParam(partName = "part1", name = "egitimKursYeriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        EgitimKursYeriSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/katalogTarama")
    @WebResult(name = "katalogTaramaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KatalogTaramaCType katalogTarama(

        @WebParam(partName = "part1", name = "katalogTaramaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KatalogTaramaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/makbuzIndir")
    @WebResult(name = "tahsilatDekontIndirC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public TahsilatDekontIndirCType makbuzIndir(

        @WebParam(partName = "part1", name = "makbuzIndirG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        MakbuzIndirGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/halUrunBilgisiSorgula")
    @WebResult(name = "halUrunBilgisiSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public HalUrunBilgisiSorgulaCType halUrunBilgisiSorgula(

        @WebParam(partName = "part1", name = "halUrunBilgisiSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        HalUrunBilgisiSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/encumenKararSorgula")
    @WebResult(name = "encumenKararSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KararSorgulaCType encumenKararSorgula(

        @WebParam(partName = "part1", name = "encumenKararSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KararSorgulaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/anonimBorcSorgula")
    @WebResult(name = "borcSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BorcSorgulamaCType anonimBorcSorgula(

        @WebParam(partName = "part1", name = "anonimBorcSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        AnonimBorcSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/basvuruTipiSorgula")
    @WebResult(name = "basvuruTipiBilgisiSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BasvuruTipiBilgisiCType basvuruTipiSorgula(

        @WebParam(partName = "part1", name = "basvuruTipiBilgisiSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/belediyeMudurlukSorgula")
    @WebResult(name = "belediyeMudurlukSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BelediyeMudurlukSorgulaCType belediyeMudurlukSorgula(

        @WebParam(partName = "part1", name = "belediyeMudurlukSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/imarBilgisiSorgula")
    @WebResult(name = "imarBilgisiSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public ImarBilgisiSorgulamaCType imarBilgisiSorgula(

        @WebParam(partName = "part1", name = "imarBilgisiSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        ImarBilgisiSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/kutuphaneUyelikSorgula")
    @WebResult(name = "kutuphaneUyelikSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public KutuphaneUyelikSorgulamaCType kutuphaneUyelikSorgula(

        @WebParam(partName = "part1", name = "kutuphaneUyelikSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/hayvanSahiplenmeBasvuruBilgileriSorgula")
    @WebResult(name = "hayvanSahiplenmeBasvuruBilgileriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public HayvanSahiplenmeBasvuruBilgileriSorgulaCType hayvanSahiplenmeBasvuruBilgileriSorgula(

        @WebParam(partName = "part1", name = "hayvanSahiplenmeBasvuruBilgileriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/nobetciEczaneSorgula")
    @WebResult(name = "nobetciEczaneSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public NobetciEczaneSorgulamaCType nobetciEczaneSorgula(

        @WebParam(partName = "part1", name = "nobetciEczaneSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        NobetciEczaneSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/bilgilendirmeIstegiSorgula")
    @WebResult(name = "bilgilendirmeIstegiSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BilgilendirmeIstegiSorgulaCType bilgilendirmeIstegiSorgula(

        @WebParam(partName = "part1", name = "bilgilendirmeIstegiSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        KisiselSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/tahsilatDekontIndir")
    @WebResult(name = "tahsilatDekontIndirC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public TahsilatDekontIndirCType tahsilatDekontIndir(

        @WebParam(partName = "part1", name = "tahsilatDekontIndirG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        TahsilatDekontIndirGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/mezarlikSorgula")
    @WebResult(name = "mezarlikSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public MezarlikSorgulaCType mezarlikSorgula(

        @WebParam(partName = "part1", name = "mezarlikSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/evrakSorgula")
    @WebResult(name = "evrakSorgulamaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public EvrakSorgulamaCType evrakSorgula(

        @WebParam(partName = "part1", name = "evrakSorgulamaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        EvrakSorgulamaGType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/cevreTemizlikBeyanYap")
    @WebResult(name = "cevreTemizlikBeyanC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public IslemSonucType cevreTemizlikBeyanYap(

        @WebParam(partName = "part1", name = "cevreTemizlikBeyanG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        CevreTemizlikBeyanType part1
    );

    @WebMethod(action = "http://belediye.turkiye.gov.tr/v3/smsBilgilendirmeTurleriSorgula")
    @WebResult(name = "smsBilgilendirmeTurleriSorgulaC", targetNamespace = "http://belediye.turkiye.gov.tr/v3", partName = "part1")
    public BelediyeBilgilendirmeTurSorgulaCType smsBilgilendirmeTurleriSorgula(

        @WebParam(partName = "part1", name = "smsBilgilendirmeTurleriSorgulaG", targetNamespace = "http://belediye.turkiye.gov.tr/v3")
        SorguParametreType part1
    );
}
