package com.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-02-14T12:06:17.240+03:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "eDevletBelediyeService",
                  wsdlLocation = "file:/Users/holdsworth/IdeaProjects/BelediyeClient/src/main/java/com/example/mockService.wsdl",
                  targetNamespace = "http://belediye.turkiye.gov.tr/v3")
public class EDevletBelediyeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://belediye.turkiye.gov.tr/v3", "eDevletBelediyeService");
    public final static QName BelediyePortTypeBindingPort = new QName("http://belediye.turkiye.gov.tr/v3", "BelediyePortTypeBindingPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/holdsworth/IdeaProjects/BelediyeClient/src/main/java/com/example/mockService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EDevletBelediyeService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/holdsworth/IdeaProjects/BelediyeClient/src/main/java/com/example/mockService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EDevletBelediyeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EDevletBelediyeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EDevletBelediyeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EDevletBelediyeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EDevletBelediyeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EDevletBelediyeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BelediyePortType
     */
    @WebEndpoint(name = "BelediyePortTypeBindingPort")
    public BelediyePortType getBelediyePortTypeBindingPort() {
        return super.getPort(BelediyePortTypeBindingPort, BelediyePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BelediyePortType
     */
    @WebEndpoint(name = "BelediyePortTypeBindingPort")
    public BelediyePortType getBelediyePortTypeBindingPort(WebServiceFeature... features) {
        return super.getPort(BelediyePortTypeBindingPort, BelediyePortType.class, features);
    }

}
